
- name: osp provisioning frontend
  hosts: jumpbox
  gather_facts: false
  tasks:
    - name: "Remove external IP"
      os_floating_ip:
        cloud: ospcloud
        state: absent
        reuse: yes
        server: appdb1-test
        network: ext_network
        wait: true
        timeout: 180
      register: serverfloatingip

    - name: Show webserver public IP
      debug: var=serverfloatingip